// @generated by protoc-gen-es-starpc none with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/template/example/example.proto (package example, syntax proto3)
/* eslint-disable */

import { EchoMsg } from "./example_pb.js";
import type { PartialMessage } from "@bufbuild/protobuf";
import { MethodKind } from "@bufbuild/protobuf";
import { buildDecodeMessageTransform, buildEncodeMessageTransform, MessageStream, ProtoRpc } from "starpc";

/**
 * Echoer service returns the given message.
 *
 * @generated from service example.Echoer
 */
export const EchoerDefinition = {
  typeName: "example.Echoer",
  methods: {
    /**
     * Echo returns the given message.
     *
     * @generated from rpc example.Echoer.Echo
     */
    Echo: {
      name: "Echo",
      I: EchoMsg,
      O: EchoMsg,
      kind: MethodKind.Unary,
    },
    /**
     * EchoServerStream is an example of a server -> client one-way stream.
     *
     * @generated from rpc example.Echoer.EchoServerStream
     */
    EchoServerStream: {
      name: "EchoServerStream",
      I: EchoMsg,
      O: EchoMsg,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * EchoClientStream is an example of client->server one-way stream.
     *
     * @generated from rpc example.Echoer.EchoClientStream
     */
    EchoClientStream: {
      name: "EchoClientStream",
      I: EchoMsg,
      O: EchoMsg,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * EchoBidiStream is an example of a two-way stream.
     *
     * @generated from rpc example.Echoer.EchoBidiStream
     */
    EchoBidiStream: {
      name: "EchoBidiStream",
      I: EchoMsg,
      O: EchoMsg,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

/**
 * Echoer service returns the given message.
 *
 * @generated from service example.Echoer
 */
export interface Echoer {
  /**
   * Echo returns the given message.
   *
   * @generated from rpc example.Echoer.Echo
   */
  Echo(
request: PartialMessage<EchoMsg>, abortSignal?: AbortSignal
): 
Promise<PartialMessage<EchoMsg>>

  /**
   * EchoServerStream is an example of a server -> client one-way stream.
   *
   * @generated from rpc example.Echoer.EchoServerStream
   */
  EchoServerStream(
request: PartialMessage<EchoMsg>, abortSignal?: AbortSignal
): 
MessageStream<EchoMsg>

  /**
   * EchoClientStream is an example of client->server one-way stream.
   *
   * @generated from rpc example.Echoer.EchoClientStream
   */
  EchoClientStream(
request: MessageStream<EchoMsg>, abortSignal?: AbortSignal
): 
Promise<PartialMessage<EchoMsg>>

  /**
   * EchoBidiStream is an example of a two-way stream.
   *
   * @generated from rpc example.Echoer.EchoBidiStream
   */
  EchoBidiStream(
request: MessageStream<EchoMsg>, abortSignal?: AbortSignal
): 
MessageStream<EchoMsg>

}

export const EchoerServiceName = EchoerDefinition.typeName

export class EchoerClient implements Echoer {
  private readonly rpc: ProtoRpc
  private readonly service: string
  constructor(rpc: ProtoRpc, opts?: { service?: string }) {
    this.service = opts?.service || EchoerServiceName
    this.rpc = rpc
    this.Echo = this.Echo.bind(this)
    this.EchoServerStream = this.EchoServerStream.bind(this)
    this.EchoClientStream = this.EchoClientStream.bind(this)
    this.EchoBidiStream = this.EchoBidiStream.bind(this)
  }
  /**
   * Echo returns the given message.
   *
   * @generated from rpc example.Echoer.Echo
   */
  async Echo(
request: PartialMessage<EchoMsg>, abortSignal?: AbortSignal
): 
Promise<PartialMessage<EchoMsg>> {
    const requestMsg = new EchoMsg(request)
    const result = await this.rpc.request(
      this.service,
      EchoerDefinition.methods.Echo.name,
      requestMsg.toBinary(),
      abortSignal || undefined,
    )
    return EchoMsg.fromBinary(result)
  }

  /**
   * EchoServerStream is an example of a server -> client one-way stream.
   *
   * @generated from rpc example.Echoer.EchoServerStream
   */
  EchoServerStream(
request: PartialMessage<EchoMsg>, abortSignal?: AbortSignal
): 
MessageStream<EchoMsg> {
    const requestMsg = new EchoMsg(request)
    const result = this.rpc.serverStreamingRequest(
      this.service,
      EchoerDefinition.methods.EchoServerStream.name,
      requestMsg.toBinary(),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(EchoMsg)(result)
  }

  /**
   * EchoClientStream is an example of client->server one-way stream.
   *
   * @generated from rpc example.Echoer.EchoClientStream
   */
  async EchoClientStream(
request: MessageStream<EchoMsg>, abortSignal?: AbortSignal
): 
Promise<PartialMessage<EchoMsg>> {
    const result = await this.rpc.clientStreamingRequest(
      this.service,
      EchoerDefinition.methods.EchoClientStream.name,
      buildEncodeMessageTransform(EchoMsg)(request),
      abortSignal || undefined,
    )
    return EchoMsg.fromBinary(result)
  }

  /**
   * EchoBidiStream is an example of a two-way stream.
   *
   * @generated from rpc example.Echoer.EchoBidiStream
   */
  EchoBidiStream(
request: MessageStream<EchoMsg>, abortSignal?: AbortSignal
): 
MessageStream<EchoMsg> {
    const result = this.rpc.bidirectionalStreamingRequest(
      this.service,
      EchoerDefinition.methods.EchoBidiStream.name,
      buildEncodeMessageTransform(EchoMsg)(request),
      abortSignal || undefined,
    )
    return buildDecodeMessageTransform(EchoMsg)(result)
  }

}
