// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/template/example/example.proto (package example, syntax proto3)
/* eslint-disable */

import {
  createMessageType,
  Message,
  MessageType,
} from '@aptre/protobuf-es-lite'

export const protobufPackage = 'example'

/**
 * EchoMsg is the message body for Echo.
 *
 * @generated from message example.EchoMsg
 */
export interface EchoMsg extends Message<EchoMsg> {
  /**
   * @generated from field: string body = 1;
   */
  body: string
}

export const EchoMsg: MessageType<EchoMsg> = createMessageType({
  typeName: 'example.EchoMsg',
  fields: [
    { no: 1, name: 'body', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ],
  packedByDefault: true,
})
